version: 2

updates:
  - package-ecosystem: "npm"
    directory: "./brainfree-auth-api" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "./brainfree-auth-ui" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "./workflows"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "./brainfree-auth-api"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "./brainfree-auth-ui"
    schedule:
      interval: "monthly"
