version: '3.8'
services:
  brainfree-auth-api:
    image: ghcr.io/fi-ml/brainfree-auth/ui:sha-a16c29f
    container_name: brainfree-auth-api
    env_file: brainfree-auth.env
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    depends_on:
      - brainfree-auth-db

  brainfree-auth-ui:
    image: ghcr.io/fi-ml/brainfree-auth/ui:sha-a16c29f
    container_name: brainfree-auth-ui
    ports:
      - "4200:4200"
    networks:
      - frontend
    depends_on:
      - brainfree-auth-api

  brainfree-auth-db:
    image: postgres:15-alpine
    container_name: brainfree-auth-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: brainfree-auth-db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U docker -d brainfree-auth-db' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

volumes:
  pgadmin_data:
    driver: local

networks:
  backend:
  frontend:
  ui:
