version: '3.8'
services:
  brainfree-auth-api:
    build:
      context: ../brainfree-auth-api
      dockerfile: Dockerfile
    container_name: brainfree-auth-api
    environment:
      APP_PORT: 3000
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: brainfree-auth-db
      DB_USERNAME: docker
      DB_PASSWORD: docker
      DB_LOGGING: false
      DB_SYNCHRONIZATION: true
      JWT_ACCESS_SECRET: PhZm9Y0rY0YqPfrv2jNCdmvO4tLiwgRU187vD0hlkNKqx4WYJctctEEH62q51HdkxWNqJFVjCKAiWM+iaaKWKNko2KeW5K2
      JWT_REFRESH_SECRET: LXNRF+5l284QWBdwO3pYp2jUFYgukkXTBLp9dpEGN8ZzKzCFo4EDdlYxZ7eHLgCmktP6s3LAReu5H4+2vhlbC4zMYg
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    depends_on:
      - brainfree-auth-db

  brainfree-auth-db:
    image: postgres:15-alpine
    container_name: brainfree-auth-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: brainfree-auth-db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U docker -d brainfree-auth-db' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

volumes:
  pgadmin_data:
    driver: local

networks:
  backend:
  frontend:
  ui:
