version: '3.8'
services:

  brainfree-auth-db:
    image: postgres:15-alpine
    container_name: brainfree-auth-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: brainfree-auth-db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U docker -d brainfree-auth-db' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

volumes:
  pgadmin_data:
    driver: local

networks:
  backend:
  ui:
