name: brainfree-auth-backend

on:
  push:
    branches: feature-brainfree-auth-ui
  pull_request:
    branches: main
    types:
      - closed

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_LOGGING: false
  DB_SYNCHRONIZATION: true
  JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}


jobs:
  create-database:
    runs-on: ubuntu-latest

    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15'

  #    container: node:10.18-jessie
  #    services:
  #      postgres:
  #        image: postgres
  #        env:
  #          POSTGRES_HOST: $DB_HOST
  #          POSTGRES_PORT: $DB_PORT
  #          POSTGRES_USER: $DB_USERNAME
  #          POSTGRES_PASSWORD: $DB_PASSWORD
  #          POSTGRES_DATABASE: $DB_NAME
  #        ports:
  #          - 5432:5432

  test:
    needs: create-database
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./brainfree-auth-api
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test

  brainfree-auth-api:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}/ui
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_AUTH_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: brainfree-auth-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
